import { ProjectType } from '@/types/projects';
import { Maradi, EH, MM, MOD, Danmuzi, DailyBoram, Sivang, Gigwanzi } from '@/assets';

export const ProjectList: ProjectType[] = [
  {
    id: 1,
    title: 'Maradi',
    period: '2022.09.01 ~ 2022.11.22',
    imageUrl: Maradi,
    skill: ['React', 'TypeScript', 'styled-components', 'axios'],
    link: 'https://github.com/DSM-Maradi/Maradi-frontend',
    introduce: '프로젝트에 펀딩을 통해 버려지는 프로젝트를 살려보아요.',
  },
  {
    id: 2,
    title: 'MM',
    period: '2022.04.01 ~ 2022.12.30',
    imageUrl: MM,
    skill: ['React', 'TypeScript', 'Emotion', 'axios'],
    link: 'https://github.com/DSM-MM/MMFrontend',
    introduce: '멘토링과 프로젝트 경험을 통해 실력을 향상시켜봐요!',
  },
  {
    id: 3,
    title: 'Daily-Boram',
    period: '2022.09.07 ~ 2022.12.09',
    imageUrl: DailyBoram,
    skill: ['React', 'JavaScript', 'styled-components', 'axios', 'recoil'],
    link: 'https://github.com/Daily-Boram/daily-boram-frontend',
    introduce: '보람 있게 소설 한편, 보람 있게 소설 한 조각. 재미와 행복을 늘 보람있게.',
  },
  {
    id: 4,
    title: 'MOD(Many Of Developers)',
    period: '2022.11.11 ~ 2022.12.16',
    imageUrl: MOD,
    skill: ['python', 'selenium', 'matplotlib', 'pandas', 'numpy', 'BeautifulSoup'],
    link: 'https://github.com/kimkh05/MOD',
    introduce: '회사에서 어떤 분야의 개발자를 더 채용할까?',
  },
  {
    id: 5,
    title: '기관지',
    period: '2022.11.03 ~ 2022.11.04',
    imageUrl: Gigwanzi,
    skill: ['React', 'JavaScript', 'styled-components', 'axios', 'recoil'],
    link: 'https://github.com/KOSA-MIDAS-HACKATHON-WEB-7/midas_frontend',
    introduce: '기록하고 관리하자! 지금 출퇴근 시간',
  },
  {
    id: 6,
    title: '단무지',
    period: '진행중',
    imageUrl: Danmuzi,
    skill: ['React', 'TypeScript', 'Nextjs', 'Emotion', 'axios', 'recoil'],
    link: 'https://github.com/DSM-DanMuZi/dsm-danmuzi-frontend',
    introduce: '대덕소프트웨어마이스터고등학교 교내 스터디 관리 서비스 단무지입니다.',
  },
  {
    id: 7,
    title: 'EH(Exercise Health)',
    period: '진행중',
    imageUrl: EH,
    skill: ['React', 'Nextjs', 'TypeScript', 'Emotion', 'axios', 'recoil'],
    link: 'https://github.com/DSM-EH/EH-front',
    introduce: '운동과 식단관리로 우리 몸을 건강하게 관리해봐요!',
  },
  {
    id: 8,
    title: 'Sivang',
    period: '진행중',
    imageUrl: Sivang,
    skill: ['React', 'vite', 'styled-components', 'axios', 'recoil', 'nestjs', 'TypeScript'],
    link: ['https://github.com/kimkh05/sivang_frontend', 'https://github.com/kimkh05/sivang_backend'],
    introduce: '자동으로 적어주는 가계부?!',
  },
];
